name: Build FFmpeg WebAssembly

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        optimization: ["O2", "O3", "Oz"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            emsdk-cache
            build
            prefix
          key: ${{ runner.os }}-emscripten-${{ matrix.optimization }}-${{ hashFiles('**/*.c', '**/*.h') }}
          restore-keys: |
            ${{ runner.os }}-emscripten-${{ matrix.optimization }}-
            ${{ runner.os }}-emscripten-

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: "latest"
          actions-cache-folder: "emsdk-cache-${{ matrix.optimization }}"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            build-essential \
            cmake \
            git \
            libass-dev \
            libtool \
            pkg-config \
            wget \
            python3 \
            nasm \
            brotli \
            wabt

      - name: Setup Build Environment
        run: |
          mkdir -p build
          mkdir -p prefix

      - name: Build x264
        run: |
          cd build
          X264_VERSION="20170226-2245-stable"
          wget https://download.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-${X264_VERSION}.tar.bz2
          tar xvfj x264-snapshot-${X264_VERSION}.tar.bz2
          cd x264-snapshot-${X264_VERSION}

          # Configure x264 with emscripten
          emconfigure ./configure \
            --prefix=$GITHUB_WORKSPACE/prefix \
            --host=i686-gnu \
            --enable-static \
            --disable-cli \
            --disable-asm \
            --disable-thread \
            --disable-opencl \
            --disable-interlaced \
            --disable-avs \
            --disable-swscale \
            --disable-lavf \
            --disable-ffms \
            --disable-gpac \
            --disable-lsmash \
            --enable-pic \
            --extra-cflags="-s USE_PTHREADS=0"

          # Build and install x264
          emmake make V=1 -j$(nproc)
          emmake make install

          # Create proper pkg-config file with absolute paths
          mkdir -p $GITHUB_WORKSPACE/prefix/lib/pkgconfig
          echo "prefix=$GITHUB_WORKSPACE/prefix" > $GITHUB_WORKSPACE/prefix/lib/pkgconfig/x264.pc
          echo "exec_prefix=\${prefix}" >> $GITHUB_WORKSPACE/prefix/lib/pkgconfig/x264.pc
          echo "libdir=\${exec_prefix}/lib" >> $GITHUB_WORKSPACE/prefix/lib/pkgconfig/x264.pc
          echo "includedir=\${prefix}/include" >> $GITHUB_WORKSPACE/prefix/lib/pkgconfig/x264.pc
          echo "" >> $GITHUB_WORKSPACE/prefix/lib/pkgconfig/x264.pc
          echo "Name: x264" >> $GITHUB_WORKSPACE/prefix/lib/pkgconfig/x264.pc
          echo "Description: x264 library for Emscripten" >> $GITHUB_WORKSPACE/prefix/lib/pkgconfig/x264.pc
          echo "Version: 0.164.x" >> $GITHUB_WORKSPACE/prefix/lib/pkgconfig/x264.pc
          echo "Requires:" >> $GITHUB_WORKSPACE/prefix/lib/pkgconfig/x264.pc
          echo "Libs: -L\${libdir} -lx264" >> $GITHUB_WORKSPACE/prefix/lib/pkgconfig/x264.pc
          echo "Libs.private: " >> $GITHUB_WORKSPACE/prefix/lib/pkgconfig/x264.pc
          echo "Cflags: -I\${includedir}" >> $GITHUB_WORKSPACE/prefix/lib/pkgconfig/x264.pc

          # Verify the content
          echo "Created x264.pc content:"
          cat $GITHUB_WORKSPACE/prefix/lib/pkgconfig/x264.pc

      - name: Upload x264 Build
        uses: actions/upload-artifact@v3
        with:
          name: x264-build
          path: ${{ github.workspace }}/prefix/**/*
          retention-days: 1

      - name: Download x264 Build
        uses: actions/download-artifact@v3
        with:
          name: x264-build
          path: ${{ github.workspace }}/prefix

      - name: Set x264 Permissions
        run: |
          chmod -R 755 ${{ github.workspace }}/prefix/lib
          chmod -R 755 ${{ github.workspace }}/prefix/include
          chmod -R 755 ${{ github.workspace }}/prefix/lib/pkgconfig
          ls -la ${{ github.workspace }}/prefix/lib/pkgconfig
          echo "PKG_CONFIG_PATH before setting:"
          echo $PKG_CONFIG_PATH
          export PKG_CONFIG_PATH="${{ github.workspace }}/prefix/lib/pkgconfig:$PKG_CONFIG_PATH"
          echo "PKG_CONFIG_PATH after setting:"
          echo $PKG_CONFIG_PATH
          echo "Testing pkg-config with absolute path:"
          pkg-config --debug --variable pc_path pkg-config
          pkg-config --debug --exists x264
          pkg-config --libs --static x264
          pkg-config --cflags x264

      - name: Configure FFmpeg
        run: |
          cd build
          wget https://ffmpeg.org/releases/ffmpeg-6.0.tar.bz2
          tar xjf ffmpeg-6.0.tar.bz2
          cd ffmpeg-6.0

          # Set environment variables
          export PKG_CONFIG_PATH="$GITHUB_WORKSPACE/prefix/lib/pkgconfig:$PKG_CONFIG_PATH"
          export PKG_CONFIG_LIBDIR="$GITHUB_WORKSPACE/prefix/lib/pkgconfig"
          export CFLAGS="-s USE_PTHREADS=0 -${{ matrix.optimization }}"
          export LDFLAGS="-L$GITHUB_WORKSPACE/prefix/lib"
          export CC="emcc"
          export CXX="em++"
          export AR="emar"
          export LD="emcc"
          export RANLIB="emranlib"

          # Debug: Show pkg-config environment
          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
          echo "Content of x264.pc:"
          cat $GITHUB_WORKSPACE/prefix/lib/pkgconfig/x264.pc
          echo "Testing pkg-config:"
          pkg-config --debug --exists x264
          pkg-config --libs --static x264
          pkg-config --cflags x264

          # Configure FFmpeg
          emconfigure ./configure \
            --prefix=$GITHUB_WORKSPACE/prefix \
            --target-os=none \
            --arch=x86_32 \
            --enable-cross-compile \
            --cc=emcc \
            --cxx=em++ \
            --ar=emar \
            --ranlib=emranlib \
            --nm=emnm \
            --disable-debug \
            --disable-x86asm \
            --disable-inline-asm \
            --disable-stripping \
            --disable-programs \
            --disable-doc \
            --disable-all \
            --enable-avcodec \
            --enable-avformat \
            --enable-swscale \
            --enable-avfilter \
            --enable-encoder=libx264,aac \
            --enable-decoder=h264,aac \
            --enable-demuxer=mov,matroska \
            --enable-muxer=mp4,mov \
            --enable-protocol=file \
            --enable-filter=scale \
            --enable-gpl \
            --enable-libx264 \
            --disable-runtime-cpudetect \
            --disable-pthreads \
            --disable-network \
            --disable-bzlib \
            --disable-zlib \
            --disable-iconv \
            --disable-asm \
            --pkg-config=pkg-config \
            --pkg-config-flags="--static" \
            --extra-cflags="-I$GITHUB_WORKSPACE/prefix/include" \
            --extra-ldflags="-L$GITHUB_WORKSPACE/prefix/lib" \
            --extra-libs="-lx264" || (cat ffbuild/config.log && false)

      - name: Build FFmpeg
        env:
          CFLAGS: "-${{ matrix.optimization }}"
        run: |
          cd build/ffmpeg-6.0
          emmake make -j$(nproc)

      - name: Compile to WebAssembly
        run: |
          cd build/ffmpeg-6.0
          emcc -${{ matrix.optimization }} \
            -s WASM=1 \
            -s TOTAL_MEMORY=33554432 \
            -s ALLOW_MEMORY_GROWTH=1 \
            -s MODULARIZE=1 \
            -s EXPORT_ES6=1 \
            -s SINGLE_FILE=1 \
            -s ENVIRONMENT='web,worker' \
            --closure 1 \
            -s NO_FILESYSTEM=1 \
            -s NO_EXIT_RUNTIME=1 \
            -s EXPORTED_RUNTIME_METHODS='["cwrap", "setValue", "getValue"]' \
            -o ffmpeg-${{ matrix.optimization }}.js \
            ffmpeg.bc

      - name: Optimize WebAssembly
        run: |
          cd build/ffmpeg-6.0
          wasm-strip ffmpeg-${{ matrix.optimization }}.wasm || true
          if command -v wasm-opt &> /dev/null; then
            wasm-opt -${{ matrix.optimization }} --enable-simd -o ffmpeg-${{ matrix.optimization }}.opt.wasm ffmpeg-${{ matrix.optimization }}.wasm || true
          else
            cp ffmpeg-${{ matrix.optimization }}.wasm ffmpeg-${{ matrix.optimization }}.opt.wasm
          fi
          brotli -o ffmpeg-${{ matrix.optimization }}.wasm.br ffmpeg-${{ matrix.optimization }}.opt.wasm

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-wasm-${{ matrix.optimization }}
          path: |
            build/ffmpeg-6.0/ffmpeg-${{ matrix.optimization }}.js
            build/ffmpeg-6.0/ffmpeg-${{ matrix.optimization }}.opt.wasm
            build/ffmpeg-6.0/ffmpeg-${{ matrix.optimization }}.wasm.br
          retention-days: 7

      - name: Report Size
        run: |
          cd build/ffmpeg-6.0
          echo "FFmpeg ${{ matrix.optimization }} build sizes:"
          echo "Original WASM size:"
          ls -lh ffmpeg-${{ matrix.optimization }}.wasm || true
          echo "Optimized WASM size:"
          ls -lh ffmpeg-${{ matrix.optimization }}.opt.wasm || true
          echo "Compressed (BR) size:"
          ls -lh ffmpeg-${{ matrix.optimization }}.wasm.br || true
